TasksEvaluation.Web/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using TasksEvaluation.Core.Interfaces.IServices;
using TasksEvaluation.Core;
using TasksEvaluation.Core.DTOs;
using TaskEvaluation.InfraStructure.Repositories.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using TasksEvaluation.Core.Entities.Business;
using TasksEvaluation.Web.ViewModels;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace TasksEvaluation.Web.Controllers
{
	public class AssignmentController : Controller
	{

		private readonly IAssignmentService _assignmentService;
		private readonly IGroupService _groupService;
		private readonly IUnitOfWork _unitOfWork;
		public AssignmentController(IAssignmentService assignmentService, IUnitOfWork unitOfWork, IGroupService groupService)
		{
			_assignmentService = assignmentService;
			_unitOfWork = unitOfWork;
			_groupService = groupService;

		}

		public async Task<IActionResult> GetAllAssignments()
		{
			var students = await _assignmentService.GetAssignmentsIncludeGroups();
			return View(students);
		}

		public ActionResult Create()
		{

			var selectedGroup = new GroupDto() { Id = 0, Title = "Select Group" };
			var allGroups = _groupService.GetAll().Result.ToList();
			allGroups.Add(selectedGroup);

			ViewBag.GroupId = new SelectList(allGroups, nameof(Group.Id), nameof(Group.Title)
				, allGroups.Find(c => c.Id == 0).Id);

			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(AssignmentDto assignment)
		{
			if (ModelState.IsValid)
			{
				await _assignmentService.Create(assignment);
				await _unitOfWork.Complete();
				return RedirectToAction(nameof(GetAllAssignments));
			}
			return View(assignment);
		}

		public async Task<IActionResult> Edit(int? id)
		{

			if (id is null || !_assignmentService.Any().Result)
				return NotFound();
			var assignment = await _assignmentService.GetById(id.Value);
			var allGroups = _groupService.GetAll().Result.ToList();
			ViewBag.GroupId = new SelectList(allGroups, nameof(Group.Id), nameof(Group.Title)
				, assignment.GroupId);
			return View(assignment);

		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(AssignmentDto assignment)
		{
			if (assignment is null || !_assignmentService.Any().Result)
				return NotFound();
			if(ModelState.IsValid)
			{
				try
				{
					_assignmentService.Update(assignment);
					await _unitOfWork.Complete();
				}
				catch (DBConcurrencyException)
				{
					if (!_assignmentService.Contains(assignment).Result)
						return NotFound();
					throw;
				}
				return RedirectToAction(nameof(GetAllAssignments));
			}
			return View(assignment);
		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id is null || !_assignmentService.Any().Result)
				return NotFound();
			var assignment = await _assignmentService.GetById(id.Value);
			return View(assignment);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (!_assignmentService.Any().Result)
				return NotFound();

			_assignmentService.Delete(id);
			await _unitOfWork.Complete();
			return RedirectToAction(nameof(GetAllAssignments));
		}

	}
}

TasksEvaluation.Web/Views/Assignment/Create.cshtml
@using TasksEvaluation.Core.DTOs 
@model AssignmentDto 

@{
	ViewData["Title"] = "Create";

}
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
	option[value = "0"] {
		display: none;
	}
</style>

<h3>Create Assignment</h3>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create" enctype="multipart/form-data">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			@*  <div  class="form-group">
			<label asp-for="Id" class="control-label"></label>
			<input asp-for="Id" class="form-control" />
			<span asp-validation-for="Id" class="text-danger"></span>
			</div> *@
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Deadline" class="control-label"></label>
				<input asp-for="Deadline" class="form-control" />
				<span asp-validation-for="Deadline" class="text-danger"></span>
			</div>




			<div class="form-group">
				<label asp-for="GroupId" class="control-label">Group</label>
				<select asp-for="GroupId" class="form-control" asp-items="@ViewBag.GroupId">
				</select>
			</div>
			<div class="form-group mt-3">
				<input type="submit" value="Create" class="btn btn-primary" />
				<a class="btn btn-secondary" asp-action="GetAllAssignments">Back to List</a>

			</div>

		</form>
	</div>
</div>

<div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

TasksEvaluation.Web/Views/Assignment/Delete.cshtml
@using TasksEvaluation.Core.DTOs

@{
	ViewData["Title"] = "Delete";
}
@model AssignmentDto

@{
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

 <div class="text-center">
	<table class="table table-bordered table-striped">
		<tr>
			<th>Assignment Title</th>
			<th>Assignment Description</th>
			<th>Assignment DeadLine</th>

		</tr>

		<tr>
			<td class="">@Model.Title</td>
			<td>@Model.Description</td>
			<td>@Model.Deadline</td>

		</tr>


	</table>
	<h3>Are you Sure to Delete @Model.Title Assignment ? </h3>
	<form asp-action="Delete">
		<div class="form-group">
			<input asp-for="Id" hidden class="form-control" />
			<input type="submit" value="Delete" class="btn btn-danger" />
			<a class="btn btn-secondary" asp-action="GetAllAssignments">Back To List</a>
		</div>


	</form>

</div>

TasksEvaluation.Web/Views/Assignment/Edit.cshtml
@using TasksEvaluation.Core.DTOs 
@model AssignmentDto 

@{
	ViewData["Title"] = "Edit";

}
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
	option[value = "0"] {
		display: none;
	}
</style>

<h3>Edit Assignment</h3>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit" enctype="multipart/form-data">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			@*  <div  class="form-group">
			<label asp-for="Id" class="control-label"></label>
			<input asp-for="Id" class="form-control" />
			<span asp-validation-for="Id" class="text-danger"></span>
			</div> *@
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Deadline" class="control-label"></label>
				<input asp-for="Deadline" class="form-control" />
				<span asp-validation-for="Deadline" class="text-danger"></span>
			</div>




			<div class="form-group">
				<label asp-for="GroupId" class="control-label">Group</label>
				<select asp-for="GroupId" class="form-control" asp-items="@ViewBag.GroupId">
				</select>
			</div>
			<div class="form-group mt-3">
				<input type="submit" value="Save" class="btn btn-primary" />
				<a class="btn btn-secondary" asp-action="GetAllAssignments">Back to List</a>

			</div>

		</form>
	</div>
</div>

<div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

TasksEvaluation.Web/Views/Assignment/GetAllAssignments.cshtml
@using TasksEvaluation.Core.DTOs 
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
@model IEnumerable<AssignmentDto> 
@{
	ViewData["Title"] = "All Assignments";
}
@if (signInManager.IsSignedIn(User))
{
	
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h4 class="">Assignment List</h4>
@if (signInManager.IsSignedIn(User)) {
	<a asp-controller="Assignment" asp-action="Create" class="btn btn-added float-end btn-info mb-3"><img src="/uploads/icons8-plus-24.png" alt="img">Add New Assignment</a>
	<p>Manage Your Assignments</p>
}

<div class="text-center">

	<table class="table table-bordered table-striped">
		<tr>
			<th>Assignment Title</th>
			<th>Assignment Description</th>
			<th>Assignment DeadLine</th>
			<th>Group</th>

			<th></th>
		</tr>
		 @foreach (var assignment in Model)
		{
			<tr>
				<td class="">@assignment.Title</td>
				<td>@assignment.Description</td>
				<td>@assignment.Deadline</td>
				<td>@assignment.Group.Title</td>

				<td>
					<a class="btn btn-primary" asp-action="Edit" asp-route-id="@assignment.Id">Edit</a>
					<a class="btn btn-danger" asp-action="Delete" asp-route-id="@assignment.Id">Delete</a>
				</td>
			</tr>

		} 
	</table>
</div>
ئ